// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDatabasePostgres(arg1:string):Promise<void>;

export function ConnectDatabaseSqlite(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;
