// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDatabasePostgres(arg1) {
  return window['go']['system']['App']['ConnectDatabasePostgres'](arg1);
}

export function ConnectDatabaseSqlite(arg1) {
  return window['go']['system']['App']['ConnectDatabaseSqlite'](arg1);
}

export function Greet(arg1) {
  return window['go']['system']['App']['Greet'](arg1);
}
