// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AButtonGroup: typeof import('@arco-design/web-vue')['ButtonGroup']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ACheckboxGroup: typeof import('@arco-design/web-vue')['CheckboxGroup']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    APagination: typeof import('@arco-design/web-vue')['Pagination']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASlider: typeof import('@arco-design/web-vue')['Slider']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATypography: typeof import('@arco-design/web-vue')['Typography']
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    BreadNav: typeof import('./src/components/app/BreadNav.vue')['default']
    ContextMenu: typeof import('./src/components/app/ContextMenu.vue')['default']
    CustomDownloadTh: typeof import('./src/components/manga/CustomDownloadTh.vue')['default']
    FooterBar: typeof import('./src/components/app/FooterBar.vue')['default']
    'IMdi:cloudSearchOutline': typeof import('~icons/mdi/cloud-search-outline')['default']
    'IMdi:eraser': typeof import('~icons/mdi/eraser')['default']
    'IMdi:formatVerticalAlignBottom': typeof import('~icons/mdi/format-vertical-align-bottom')['default']
    'IMdi:formatVerticalAlignTop': typeof import('~icons/mdi/format-vertical-align-top')['default']
    IMdiEmoticonSadOutline: typeof import('~icons/mdi/emoticon-sad-outline')['default']
    ITwemojiFlagForFlagIndonesia: typeof import('~icons/twemoji/flag-for-flag-indonesia')['default']
    ITwemojiFlagForFlagUnitedKingdom: typeof import('~icons/twemoji/flag-for-flag-united-kingdom')['default']
    MenuBar: typeof import('./src/components/app/MenuBar.vue')['default']
    PageNav: typeof import('./src/components/manga/PageNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/app/SideBar.vue')['default']
    TitleBar: typeof import('./src/components/app/TitleBar.vue')['default']
  }
}
