// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoConvert(arg1) {
  return window['go']['file']['Convert']['DoConvert'](arg1);
}
