// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindFileByExt(arg1, arg2) {
  return window['go']['file']['FilesDataReader']['FindFileByExt'](arg1, arg2);
}

export function GetFileManga() {
  return window['go']['file']['FilesDataReader']['GetFileManga']();
}
