// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindFileByExt(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function GetFileManga():Promise<Array<string>>;
