// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlterManga(arg1) {
  return window['go']['manga']['Alter']['GetAlterManga'](arg1);
}

export function GetAlters() {
  return window['go']['manga']['Alter']['GetAlters']();
}

export function SetAlter(arg1) {
  return window['go']['manga']['Alter']['SetAlter'](arg1);
}

export function TableName() {
  return window['go']['manga']['Alter']['TableName']();
}
