// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manga} from '../models';

export function GetAlterManga(arg1:number):Promise<Array<manga.Alter>>;

export function GetAlters():Promise<Array<manga.Alter>>;

export function SetAlter(arg1:manga.Alter):Promise<void>;

export function TableName():Promise<string>;
