// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteChapterBatch(arg1) {
  return window['go']['manga']['Chapter']['DeleteChapterBatch'](arg1);
}

export function GetChapter(arg1) {
  return window['go']['manga']['Chapter']['GetChapter'](arg1);
}

export function InsertChapter(arg1) {
  return window['go']['manga']['Chapter']['InsertChapter'](arg1);
}

export function InsertChapterBatch(arg1) {
  return window['go']['manga']['Chapter']['InsertChapterBatch'](arg1);
}

export function UpdateRead(arg1, arg2) {
  return window['go']['manga']['Chapter']['UpdateRead'](arg1, arg2);
}
