// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manga} from '../models';

export function DeleteChapterBatch(arg1:Array<manga.Chapter>):Promise<number>;

export function GetChapter(arg1:number):Promise<manga.Chapter>;

export function InsertChapter(arg1:manga.Chapter):Promise<number>;

export function InsertChapterBatch(arg1:Array<manga.Chapter>):Promise<any>;
