// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manga} from '../models';

export function GetChapter(arg1:number):Promise<manga.Chapter>;
