// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChapter(arg1) {
  return window['go']['manga']['Chapter']['GetChapter'](arg1);
}

export function InsertChapter(arg1) {
  return window['go']['manga']['Chapter']['InsertChapter'](arg1);
}
