// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manga} from '../models';

export function AutoScanDirs():Promise<Array<string>>;

export function ClearAllConfig():Promise<void>;

export function GetConfig():Promise<manga.Config>;

export function MigrateServer():Promise<boolean>;

export function SetConfig(arg1:manga.Config):Promise<void>;
