// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoScanDirs() {
  return window['go']['manga']['Config']['AutoScanDirs']();
}

export function ClearAllConfig() {
  return window['go']['manga']['Config']['ClearAllConfig']();
}

export function GetConfig() {
  return window['go']['manga']['Config']['GetConfig']();
}

export function SetConfig(arg1) {
  return window['go']['manga']['Config']['SetConfig'](arg1);
}
