// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manga} from '../models';

export function GetManga(arg1:number):Promise<manga.Manga>;

export function GetMangaHome(arg1:any,arg2:number,arg3:number):Promise<manga.MangaHome>;

export function GetMangaWithChapter(arg1:number):Promise<manga.Manga>;

export function GetMangas():Promise<Array<manga.Manga>>;

export function GetPage(arg1:number):Promise<manga.Page>;

export function GetServer():Promise<Array<manga.Server>>;
