// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletMangaOnly(arg1) {
  return window['go']['manga']['Manga']['DeletMangaOnly'](arg1);
}

export function DeleteMangaWithFile(arg1) {
  return window['go']['manga']['Manga']['DeleteMangaWithFile'](arg1);
}

export function GetCountMangas() {
  return window['go']['manga']['Manga']['GetCountMangas']();
}

export function GetManga(arg1) {
  return window['go']['manga']['Manga']['GetManga'](arg1);
}

export function GetMangaHome(arg1, arg2, arg3, arg4) {
  return window['go']['manga']['Manga']['GetMangaHome'](arg1, arg2, arg3, arg4);
}

export function GetMangaWithAlter(arg1) {
  return window['go']['manga']['Manga']['GetMangaWithAlter'](arg1);
}

export function GetMangaWithChapter(arg1) {
  return window['go']['manga']['Manga']['GetMangaWithChapter'](arg1);
}

export function GetMangas() {
  return window['go']['manga']['Manga']['GetMangas']();
}

export function GetPage(arg1) {
  return window['go']['manga']['Manga']['GetPage'](arg1);
}

export function GetRandomMangaHome(arg1) {
  return window['go']['manga']['Manga']['GetRandomMangaHome'](arg1);
}

export function GetServer() {
  return window['go']['manga']['Manga']['GetServer']();
}

export function InsertManga(arg1) {
  return window['go']['manga']['Manga']['InsertManga'](arg1);
}

export function TestHomeApiQuery() {
  return window['go']['manga']['Manga']['TestHomeApiQuery']();
}

export function UpdateChapJS(arg1, arg2) {
  return window['go']['manga']['Manga']['UpdateChapJS'](arg1, arg2);
}

export function UpdatePagesJS(arg1, arg2) {
  return window['go']['manga']['Manga']['UpdatePagesJS'](arg1, arg2);
}
