// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadChapter(arg1) {
  return window['go']['download']['Download']['DownloadChapter'](arg1);
}

export function DownloadPage(arg1) {
  return window['go']['download']['Download']['DownloadPage'](arg1);
}
