// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetChapter(arg1:types.Option):Promise<types.Chapter>;

export function GetPage(arg1:types.Option):Promise<types.Page>;
