// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckChapterDB(arg1) {
  return window['go']['download']['Download']['CheckChapterDB'](arg1);
}

export function DownloadJS(arg1) {
  return window['go']['download']['Download']['DownloadJS'](arg1);
}

export function GetChapter(arg1) {
  return window['go']['download']['Download']['GetChapter'](arg1);
}

export function GetChapterMdexPagination(arg1, arg2, arg3) {
  return window['go']['download']['Download']['GetChapterMdexPagination'](arg1, arg2, arg3);
}

export function GetPage(arg1) {
  return window['go']['download']['Download']['GetPage'](arg1);
}

export function SaveMangaCover(arg1) {
  return window['go']['download']['Download']['SaveMangaCover'](arg1);
}
