// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';
import {types} from '../models';

export function DownloadChapter(arg1:download.Option):Promise<types.Chapter>;

export function DownloadPage(arg1:download.Option):Promise<types.Page>;
