// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChapter(arg1) {
  return window['go']['download']['Download']['GetChapter'](arg1);
}

export function GetPage(arg1) {
  return window['go']['download']['Download']['GetPage'](arg1);
}
