// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {download} from '../models';
import {internet} from '../models';

export function CheckChapterDB(arg1:types.Chapter):Promise<types.Chapter>;

export function DownloadJS(arg1:download.ParamJS):Promise<Array<internet.StatDownload>>;

export function GetChapter(arg1:types.Option):Promise<types.Chapter>;

export function GetChapterMdexPagination(arg1:string,arg2:number,arg3:number):Promise<Array<types.ChapterList>>;

export function GetPage(arg1:types.Chapter):Promise<download.PageReport>;

export function RetryDownloads(arg1:number,arg2:Array<internet.StatDownload>):Promise<Array<internet.StatDownload>>;

export function SaveMangaCover(arg1:types.Chapter):Promise<number>;
