// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MessageBox(arg1, arg2) {
  return window['go']['tool']['Dialog']['MessageBox'](arg1, arg2);
}

export function MessageBoxError(arg1, arg2) {
  return window['go']['tool']['Dialog']['MessageBoxError'](arg1, arg2);
}

export function MessageBoxQuestion(arg1, arg2) {
  return window['go']['tool']['Dialog']['MessageBoxQuestion'](arg1, arg2);
}

export function OpenDialog(arg1, arg2, arg3, arg4) {
  return window['go']['tool']['Dialog']['OpenDialog'](arg1, arg2, arg3, arg4);
}

export function SaveDialog(arg1, arg2, arg3, arg4) {
  return window['go']['tool']['Dialog']['SaveDialog'](arg1, arg2, arg3, arg4);
}
