// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MessageBox(arg1:string,arg2:string):Promise<string>;

export function MessageBoxError(arg1:string,arg2:string):Promise<string>;

export function MessageBoxQuestion(arg1:string,arg2:string):Promise<string>;

export function OpenDialog(arg1:string,arg2:string,arg3:string,arg4:Array<{[key: string]: string}>):Promise<string>;

export function SaveDialog(arg1:string,arg2:string,arg3:string,arg4:Array<{[key: string]: string}>):Promise<string>;
