// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch(arg1) {
  return window['go']['tool']['Web']['Fetch'](arg1);
}

export function FetchPost(arg1, arg2) {
  return window['go']['tool']['Web']['FetchPost'](arg1, arg2);
}

export function WebBrowser(arg1) {
  return window['go']['tool']['Web']['WebBrowser'](arg1);
}
