// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tool} from '../models';

export function WebBrowser(arg1:string):Promise<tool.Web>;
