// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch(arg1:string):Promise<string>;

export function FetchPost(arg1:string,arg2:any):Promise<string>;

export function WebBrowser(arg1:string):Promise<any>;
